<?php

namespace ContainerUmfBFoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SRO4o_LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SRO4o.L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SRO4o.L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'room' => ['privates', '.errored..service_locator.SRO4o.L.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.SRO4o.L": it needs an instance of "App\\Entity\\Room" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'room' => 'App\\Entity\\Room',
        ]);
    }
}
