<?php

namespace ContainerUmfBFoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7Dwj5GAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7Dwj5GA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7Dwj5GA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'defense' => ['privates', '.errored..service_locator.7Dwj5GA.App\\Entity\\Defense', NULL, 'Cannot autowire service ".service_locator.7Dwj5GA": it needs an instance of "App\\Entity\\Defense" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'defense' => 'App\\Entity\\Defense',
            'entityManager' => '?',
        ]);
    }
}
