<?php

namespace ContainerUmfBFoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3cP3GvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3c_p3Gv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3c_p3Gv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminDashboardController::index' => ['privates', '.service_locator.5z7wjvF', 'get_ServiceLocator_5z7wjvFService', true],
            'App\\Controller\\DefenseController::delete' => ['privates', '.service_locator.7Dwj5GA', 'get_ServiceLocator_7Dwj5GAService', true],
            'App\\Controller\\DefenseController::edit' => ['privates', '.service_locator.qzMR3AG', 'get_ServiceLocator_QzMR3AGService', true],
            'App\\Controller\\DefenseController::index' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Controller\\DefenseController::new' => ['privates', '.service_locator.qjJP_P3', 'get_ServiceLocator_QjJPP3Service', true],
            'App\\Controller\\RoomController::delete' => ['privates', '.service_locator.SRO4o.L', 'get_ServiceLocator_SRO4o_LService', true],
            'App\\Controller\\RoomController::edit' => ['privates', '.service_locator.SRO4o.L', 'get_ServiceLocator_SRO4o_LService', true],
            'App\\Controller\\RoomController::index' => ['privates', '.service_locator.0.E_r2b', 'get_ServiceLocator_0_ER2bService', true],
            'App\\Controller\\RoomController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StudentController::delete' => ['privates', '.service_locator.zWpgj9V', 'get_ServiceLocator_ZWpgj9VService', true],
            'App\\Controller\\StudentController::edit' => ['privates', '.service_locator.zWpgj9V', 'get_ServiceLocator_ZWpgj9VService', true],
            'App\\Controller\\StudentController::index' => ['privates', '.service_locator.wmzwuy.', 'get_ServiceLocator_Wmzwuy_Service', true],
            'App\\Controller\\StudentController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TeacherController::delete' => ['privates', '.service_locator.WUvpX68', 'get_ServiceLocator_WUvpX68Service', true],
            'App\\Controller\\TeacherController::edit' => ['privates', '.service_locator.WUvpX68', 'get_ServiceLocator_WUvpX68Service', true],
            'App\\Controller\\TeacherController::index' => ['privates', '.service_locator.oO4XDkC', 'get_ServiceLocator_OO4XDkCService', true],
            'App\\Controller\\TeacherController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TeacherDashboardController::defenses' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Controller\\TeacherDashboardController::index' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Controller\\TeacherDashboardController::jurys' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminDashboardController:index' => ['privates', '.service_locator.5z7wjvF', 'get_ServiceLocator_5z7wjvFService', true],
            'App\\Controller\\DefenseController:delete' => ['privates', '.service_locator.7Dwj5GA', 'get_ServiceLocator_7Dwj5GAService', true],
            'App\\Controller\\DefenseController:edit' => ['privates', '.service_locator.qzMR3AG', 'get_ServiceLocator_QzMR3AGService', true],
            'App\\Controller\\DefenseController:index' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Controller\\DefenseController:new' => ['privates', '.service_locator.qjJP_P3', 'get_ServiceLocator_QjJPP3Service', true],
            'App\\Controller\\RoomController:delete' => ['privates', '.service_locator.SRO4o.L', 'get_ServiceLocator_SRO4o_LService', true],
            'App\\Controller\\RoomController:edit' => ['privates', '.service_locator.SRO4o.L', 'get_ServiceLocator_SRO4o_LService', true],
            'App\\Controller\\RoomController:index' => ['privates', '.service_locator.0.E_r2b', 'get_ServiceLocator_0_ER2bService', true],
            'App\\Controller\\RoomController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StudentController:delete' => ['privates', '.service_locator.zWpgj9V', 'get_ServiceLocator_ZWpgj9VService', true],
            'App\\Controller\\StudentController:edit' => ['privates', '.service_locator.zWpgj9V', 'get_ServiceLocator_ZWpgj9VService', true],
            'App\\Controller\\StudentController:index' => ['privates', '.service_locator.wmzwuy.', 'get_ServiceLocator_Wmzwuy_Service', true],
            'App\\Controller\\StudentController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TeacherController:delete' => ['privates', '.service_locator.WUvpX68', 'get_ServiceLocator_WUvpX68Service', true],
            'App\\Controller\\TeacherController:edit' => ['privates', '.service_locator.WUvpX68', 'get_ServiceLocator_WUvpX68Service', true],
            'App\\Controller\\TeacherController:index' => ['privates', '.service_locator.oO4XDkC', 'get_ServiceLocator_OO4XDkCService', true],
            'App\\Controller\\TeacherController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\TeacherDashboardController:defenses' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Controller\\TeacherDashboardController:index' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'App\\Controller\\TeacherDashboardController:jurys' => ['privates', '.service_locator.v72.VIN', 'get_ServiceLocator_V72_VINService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminDashboardController::index' => '?',
            'App\\Controller\\DefenseController::delete' => '?',
            'App\\Controller\\DefenseController::edit' => '?',
            'App\\Controller\\DefenseController::index' => '?',
            'App\\Controller\\DefenseController::new' => '?',
            'App\\Controller\\RoomController::delete' => '?',
            'App\\Controller\\RoomController::edit' => '?',
            'App\\Controller\\RoomController::index' => '?',
            'App\\Controller\\RoomController::new' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StudentController::delete' => '?',
            'App\\Controller\\StudentController::edit' => '?',
            'App\\Controller\\StudentController::index' => '?',
            'App\\Controller\\StudentController::new' => '?',
            'App\\Controller\\TeacherController::delete' => '?',
            'App\\Controller\\TeacherController::edit' => '?',
            'App\\Controller\\TeacherController::index' => '?',
            'App\\Controller\\TeacherController::new' => '?',
            'App\\Controller\\TeacherDashboardController::defenses' => '?',
            'App\\Controller\\TeacherDashboardController::index' => '?',
            'App\\Controller\\TeacherDashboardController::jurys' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminDashboardController:index' => '?',
            'App\\Controller\\DefenseController:delete' => '?',
            'App\\Controller\\DefenseController:edit' => '?',
            'App\\Controller\\DefenseController:index' => '?',
            'App\\Controller\\DefenseController:new' => '?',
            'App\\Controller\\RoomController:delete' => '?',
            'App\\Controller\\RoomController:edit' => '?',
            'App\\Controller\\RoomController:index' => '?',
            'App\\Controller\\RoomController:new' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StudentController:delete' => '?',
            'App\\Controller\\StudentController:edit' => '?',
            'App\\Controller\\StudentController:index' => '?',
            'App\\Controller\\StudentController:new' => '?',
            'App\\Controller\\TeacherController:delete' => '?',
            'App\\Controller\\TeacherController:edit' => '?',
            'App\\Controller\\TeacherController:index' => '?',
            'App\\Controller\\TeacherController:new' => '?',
            'App\\Controller\\TeacherDashboardController:defenses' => '?',
            'App\\Controller\\TeacherDashboardController:index' => '?',
            'App\\Controller\\TeacherDashboardController:jurys' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
