<?php

namespace ContainerUmfBFoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5z7wjvFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5z7wjvF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5z7wjvF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'defenseRepository' => ['privates', 'App\\Repository\\DefenseRepository', 'getDefenseRepositoryService', true],
            'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService', true],
            'studentRepository' => ['privates', 'App\\Repository\\StudentRepository', 'getStudentRepositoryService', true],
            'teacherRepository' => ['privates', 'App\\Repository\\TeacherRepository', 'getTeacherRepositoryService', true],
        ], [
            'defenseRepository' => 'App\\Repository\\DefenseRepository',
            'roomRepository' => 'App\\Repository\\RoomRepository',
            'studentRepository' => 'App\\Repository\\StudentRepository',
            'teacherRepository' => 'App\\Repository\\TeacherRepository',
        ]);
    }
}
