<?php

namespace ContainerUmfBFoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefenseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7Dwj5GA.App\Entity\Defense' shared service.
     *
     * @return \App\Entity\Defense
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.7Dwj5GA": it needs an instance of "App\\Entity\\Defense" but this type has been excluded in "config/services.yaml".');
    }
}
