<?php

namespace ContainerUmfBFoQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.SRO4o.L.App\Entity\Room' shared service.
     *
     * @return \App\Entity\Room
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.SRO4o.L": it needs an instance of "App\\Entity\\Room" but this type has been excluded in "config/services.yaml".');
    }
}
