<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmfBFoQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmfBFoQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmfBFoQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmfBFoQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmfBFoQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmfBFoQ',
    'container.build_id' => '34468eda',
    'container.build_time' => 1784727863,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmfBFoQ');
